CREATE TABLE "companies" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"hq" text NOT NULL,
	"sector" text NOT NULL,
	"stage" text NOT NULL,
	"funding" text NOT NULL,
	"what_they_do" text NOT NULL,
	"interesting_angle" text NOT NULL,
	"website" text,
	"founded" text,
	"b_corp" text,
	"target_customer" text,
	"last_updated" text,
	"sources" text,
	"notes" text,
	"jobs_url" text,
	"linkedin_url" text,
	"twitter_url" text,
	"facebook_url" text,
	"instagram_url" text,
	"youtube_url" text,
	"crunchbase_url" text,
	"pitchbook_url" text,
	"builtin_url" text,
	"lat" double precision,
	"lng" double precision,
	CONSTRAINT "companies_slug_unique" UNIQUE("slug")
);
